from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol


@dataclass(frozen=True)
class AdapterStatus:
    name: str
    available: bool
    running: bool = False
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class StreamConfig:
    width: int = 1280
    height: int = 720
    fps: int = 30
    format: str = "unknown"
    extra: dict[str, Any] = field(default_factory=dict)


class CameraAdapter(Protocol):
    def list_devices(self) -> list[dict[str, Any]]: ...
    def list_formats(self, device_id: str | None = None) -> list[dict[str, Any]]: ...
    def start_stream(self, config: StreamConfig) -> AdapterStatus: ...
    def stop_stream(self) -> AdapterStatus: ...
    def get_status(self) -> AdapterStatus: ...


class DisplayAdapter(Protocol):
    def list_displays(self) -> list[dict[str, Any]]: ...
    def start_session(self, config: dict[str, Any]) -> AdapterStatus: ...
    def stop_session(self) -> AdapterStatus: ...
    def get_status(self) -> AdapterStatus: ...


class VideoEncoderAdapter(Protocol):
    def list_encoders(self) -> list[dict[str, Any]]: ...
    def start_encoder(self, config: StreamConfig) -> AdapterStatus: ...
    def stop_encoder(self) -> AdapterStatus: ...
    def get_status(self) -> AdapterStatus: ...


class RadioAdapter(Protocol):
    def send_packet(self, payload: bytes) -> AdapterStatus: ...
    def receive_packet(self, timeout_s: float = 0.0) -> bytes | None: ...
    def get_status(self) -> AdapterStatus: ...


class PowerAdapter(Protocol):
    def get_state(self) -> dict[str, Any]: ...
    def set_mode(self, mode: str) -> AdapterStatus: ...
    def get_status(self) -> AdapterStatus: ...


class M4Bridge(Protocol):
    def send_command(self, command: str, payload: dict[str, Any] | None = None) -> AdapterStatus: ...
    def get_status(self) -> AdapterStatus: ...


class FpgaBridge(Protocol):
    def configure(self, image_path: str) -> AdapterStatus: ...
    def read_packet(self) -> bytes | None: ...
    def get_status(self) -> AdapterStatus: ...


class SensorAdapter(Protocol):
    def list_sensors(self) -> list[dict[str, Any]]: ...
    def read_sample(self, sensor_id: str) -> dict[str, Any] | None: ...
    def get_status(self) -> AdapterStatus: ...


class StorageAdapter(Protocol):
    def write_record(self, name: str, payload: bytes) -> AdapterStatus: ...
    def read_record(self, name: str) -> bytes | None: ...
    def get_status(self) -> AdapterStatus: ...


class AudioAdapter(Protocol):
    def start_capture(self, config: dict[str, Any]) -> AdapterStatus: ...
    def stop_capture(self) -> AdapterStatus: ...
    def get_status(self) -> AdapterStatus: ...
